### ISSUE TITLE
Changes suggested by Hlint

### ISSUE THREAD

**Issue by ExcaliburZero** [vincenthz/hs-cli#11]
I recently ran Hlint over the source files of the library and there are a few good changes that it suggested. Mainly these changes consist of using more specific Maybe functions, such as changing uses of `maybe a id b` into `fromMaybe a b`, and removing unneeded syntax, such as unnecessary do notations.

Making the changes suggested by Hlint will help to improve the readability and expressiveness of the  source code.

I used the following command to run Hlint on all of the source files.

```
$ hlint $(find . | grep "hs" | grep -v "dist")
```

I'll try putting together a pull request to make the various changes.

**Comment by vincenthz** [comment]
I'm not generally too much a fan of hlint suggestions. some of them make sense and are nice improvements but some don't actually change anything (like removing do's) or change a combinator to another combinator that personally I found a bit too obscure. hlint is also not aware of code symmetry or personal preferences:

To illustrate what I'm talking about:

```
    when (x)     $ ...
    when (y)     $ ...
    when (not z) $ ...
```

```
    when (x)    $ ...
    when (y)    $ ...
    unless (z)  $ ...
```

I'm sure some people might prefer the second version, but I prefer the first as you don't have to juggle the set of conditions in your head.

**Comment by ExcaliburZero** [comment]
@vincenthz  That makes sense.

A number of the suggestions are like the ones that you mention, but a few are more useful. I'll try going through the Hlint suggestions and make a list of the ones that seem more useful.

**Comment by ExcaliburZero** [comment]
After looking though the Hlint suggestions, theses ones seemed to be the more useful ones:

```
./Console/Display.hs:369:21: Suggestion: Redundant $
Found:
  T $ rowSep
Why not:
  T rowSep
```

This is just an unused `$`. Actually with the extra `$` it also does not match the similar pattern of `T "\n"`.

```
./Console/Options/Types.hs:119:9: Warning: Use isJust
Found:
  maybe False (const True)
Why not:
  Data.Maybe.isJust
```

The `isJust` function is a bit more expressive in this case, and is a good bit easier to understand than `maybe False (const True)`.

```
./Console/Options.hs:39:1: Warning: Unused LANGUAGE pragma
Found:
  {-# LANGUAGE GeneralizedNewtypeDeriving #-}
Why not remove it
```

This language pragma is just unused, so there isn't really any need for it to be in the file. If it is needed later then it could just be re-added.

**Comment by vincenthz** [comment]
yeah, the one you mention are fine. 1 and 3 is probably linked to code that was different before and then when it got changed but all what could be adapt wasn't

**Comment by ExcaliburZero** [comment]
I have made a pull request with those changes here: #13
