### ISSUE TITLE
Add more generated files to gitignore

### ISSUE THREAD

**Issue by ExcaliburZero** [vincenthz/hs-cli#12]
Currently the gitignore file is set to only ignore a few types of Haskell generated files. However, it does not currently cover things such as Cabal sandbox files, so such files will continually show up when using `git status`, even when they shouldn't be committed to the repository.

This issue could be solved by adding rules to ignore such files to the gitignore file. Specifically I'd recommend using the rules defined on the following page, as they cover most of the possible Haskell generated files.

https://www.gitignore.io/api/haskell

**Comment by vincenthz** [comment]
yes, definitely please add what you think is relevant
