### ISSUE TITLE
Print argument info on missing argument(s)

### ISSUE THREAD

**Issue by ExcaliburZero** [vincenthz/hs-cli#8]
Currently whenever a required argument is not included in the command, the following error message is given.

```
error: missing arguments
```

This information does not tell the user much about the issue that they are having. It could be improved by listing what the command arguments are, as well as a pointer to the program help information.

```
error: missing arguments

cli-program FILEPATH

Run the program with the "--help" flag for more usage info.
```

**Comment by vincenthz** [comment]
duped of #3
