### ISSUE TITLE
Document how to use progress bars

### ISSUE THREAD

**Issue by ExcaliburZero** [vincenthz/hs-cli#9]
Currently the documentation on how to use progress bars in `Console.Display` is very unclear. I have tried reading the documentation and looking at the source code of the library, but it is not clear on how to use progress bars.

From the best I can tell, it seems to be a work-flow like the following. However, the following code only seems to print out a blank line and change the terminal text color to white.

```
d <- displayInit
_ <- progress d 10 progressTick
```

From the documentation it is clear that the `progress` function must be used in some capacity, however its use and arguments are not fully clear.

```
progress :: TerminalDisplay -> Int -> (ProgressBar -> IO a) -> IO a
```

It first takes in a TerminalDisplay, which is presumably generated via `displayInit`. However, the second argument is just noted as being an Int with no further documentation. After looking through the function source code I found that the Int appears to be the number of items which the progress bar represents. This fact should be documented in the function signature in order to make it more clear.

The third argument is a function `ProgressBar -> IO a`. From the available exported functions, the only function with such a signature is `progressTick`, so presumably that function would be used for this argument.

```
progressTick :: ProgressBar -> IO ()
```

It is also unclear as to how a given progress bar would be updated. From the documentation it sounds as if the `progressTick` function would perform this task, however as the exported functions do not provide away to obtain a `ProgressBar`, it is unclear as to how it would be used.

---

Sorry for the wall of text. It's just that I tried to work on using a progress bar in an application and I was not able to figure out how to use one after a good while of trying.

If you can explain and show how progress bars are meant to be used, I would be glad to help you improve the library documentation on them.

**Comment by NicolasDP** [comment]
I agree that the documentation is not very clear.

I think you are nearly there. The function `ProgressBar -> IO a` is actually the function which needs to be executed and this function will be able to update the progress bar with the given `ProgressBar`.

``` Haskell
module Main (main) where

import Console.Options
import Console.Display
import Control.Concurrent.Thread.Delay (delay)

import Data.Version (makeVersion)

progression :: IO String
progression = do
    td <- displayInit
    progress td 100 $ loop 100
  where
    loop :: Int -> ProgressBar -> IO String
    loop 0 _  = return "End of the work"
    loop n pb = do
        progressTick pb
        delay 100000
        loop (n - 1) pb

main :: IO ()
main = defaultMain $ do
  programName "test"
  programVersion $ makeVersion [0,0,1]
  programDescription "test the progress bar"
  command "new" $ do
    description "create a new progress bar"
    action $ \_ -> progression >>= print
```

I haven't tried it yet, but I think this is how it was meant to be use.

**Comment by ExcaliburZero** [comment]
@NicolasDP Thanks! That example really cleared it up for me.

I'll try to see if I can put together some better documentation for the functions.

**Comment by ExcaliburZero** [comment]
I have written up some documentation for progress bars, and have opened a pull request for the changes here: #10

**Comment by vincenthz** [comment]
Very useful, thanks again
